# Generated by Django 5.1.7 on 2025-03-23 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_shipment_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
