# Generated by Django 5.1.1 on 2025-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_shipment_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('dispatcher', 'Dispatcher'), ('courier', 'Courier')], default='customer', max_length=20),
        ),
    ]
