# Generated by Django 5.1.1 on 2025-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='shipment',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
