# Generated by Django 5.1.1 on 2025-03-30 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_shipment_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
